services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/kafka/data
    networks:
      - kafka-network

  api:
    container_name: 'kafka-api'
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    command: "npm run start:dev"
    env_file:
      - api/.env
    networks:
      - kafka-network
    depends_on:
      - kafka-mongo
      - kafka

  kafka-consumer:
    container_name: 'kafka-consumer'
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile
    volumes:
      - ./kafka-consumer:/app
      - ./kafka-consumer/node_modules:/app/node_modules
    command: "npm run start:dev"
    env_file:
      - ./kafka-consumer/.env
    depends_on:
      - kafka
    networks:
      - kafka-network

  kafka-mongo:
    container_name: 'kafka-mongo'
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - kafka-mongo-data:/data/db
    networks:
      - kafka-network

volumes:
  kafka-mongo-data:

networks:
  kafka-network:
    driver: bridge