services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/lib/kafka/data
    networks:
      - kafka-network

  api:
    container_name: 'kafka-api-service'
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-service:/app
      - ./api-service/node_modules:/app/node_modules
    command: "npm run start:dev"
    env_file:
      - ./api-service/.env
    networks:
      - kafka-network
    depends_on:
      - mongo
      - kafka

  mongo:
    container_name: 'kafka-mongo'
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - kafka-mongo-data:/data/db
    networks:
      - kafka-network

volumes:
  kafka-mongo-data:

networks:
  kafka-network:
    driver: bridge