version: '3.8'
services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-service:/app
      - ./api-service/node_modules:/app/node_modules
    command: "npm run start:dev"
    environment:
      - MONGO_URI=mongodb://mongo:27017/api-db
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - kafka-mongo-data:/data/db

volumes:
  kafka-mongo-data:
